name: build and test

on:
  push:
  pull_request:
    branches: [ master ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '6.0.101'

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: WabiSabi "Unit" Tests
      run: dotnet test --no-restore --filter "(FullyQualifiedName!~Integration)&(FullyQualifiedName~WabiSabi)" --logger "console;verbosity=detailed"

    - name: Other "Unit" Tests
      run: dotnet test --no-restore --filter "(FullyQualifiedName~UnitTests)&(FullyQualifiedName!~WabiSabi)" --logger "console;verbosity=detailed"

    - name: Build (Release)
      run: dotnet build --configuration Release --no-restore
    
    - name: '"Integration" "Unit" Tests'
      run: dotnet test --configuration Release --no-restore --filter "(FullyQualifiedName~UnitTests)&(FullyQualifiedName~Integration)" --logger "console;verbosity=detailed"

    - name: '"Integration" Tests'
      run: dotnet test --configuration Release --no-restore --filter "(FullyQualifiedName!~UnitTests)" --logger "console;verbosity=detailed"
