name: test

on:
  push:
  pull_request:
    branches: [ master ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '6.0.101'

jobs:
  test:

    name: test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: WabiSabi "Unit" Tests
      run: dotnet test --no-build --filter "(FullyQualifiedName!~Integration)&(FullyQualifiedName~WabiSabi)" --logger "console;verbosity=detailed" --collect:"XPlat Code Coverage" --logger trx

    - name: Other "Unit" Tests
      run: dotnet test --no-build --filter "(FullyQualifiedName~UnitTests)&(FullyQualifiedName!~WabiSabi)" --logger "console;verbosity=detailed" --collect:"XPlat Code Coverage" --logger trx 

    - name: '"Integration" "Unit" Tests'
      run: dotnet test --no-build --filter "(FullyQualifiedName~UnitTests)&(FullyQualifiedName~Integration)" --logger "console;verbosity=detailed" --collect:"XPlat Code Coverage" --logger trx 

    #- name: '"Integration" Tests'
    #  run: dotnet test --no-build --filter "(FullyQualifiedName!~UnitTests)" --logger "console;verbosity=detailed" --collect:"XPlat Code Coverage" --logger trx

    - uses: actions/upload-artifact@v2
      with:
        name: TestResults
        path: WalletWasabi.Tests/TestResults

    - uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
